'''
        TIJD:    22 min
        geschat: 45 min

'''


class Airline:

    def __init__(self, name):
        self.__name_ = name
        self.__flights_ = dict()

    def get_name(self):
        return self.__name_

    def set_name(self, name):
        self.__name_ = name

    def get_departure_airports(self):
        return self.__flights_

    def get_nb_departure_airports(self):
        return len(self.get_departure_airports().keys())

    def get_all_destinations_for(self, departure):
        return frozenset(self.get_departure_airports().get(departure, frozenset()))

    def has_flight_from_to(self, departure, destination):
        return destination in self.get_all_destinations_for(departure)

    def add_destination_for(self, departure, destinations):
        self.get_departure_airports()[departure] = \
            self.get_all_destinations_for(departure).union(frozenset(destinations))

    def remove_destination_for(self, departure, destination):
        if destination in self.get_all_destinations_for(departure):
            self.get_departure_airports()[departure] = \
                self.get_all_destinations_for(departure) - frozenset(destination)
        if len(self.get_all_destinations_for(departure)) == 0:
            del self.get_departure_airports()[departure]

    def get_all_departures_for(self, destination):
        return frozenset(
                map(lambda departures, _: departures,
                    filter(lambda departures, destinations: destination in destinations,
                           self.get_departure_airports().items())))

    def __add__(self, other):
        self.set_name(self.get_name() + " " + other.get_name())
        for departure in other.get_departure_airports():
            self.add_destination_for(departure, other.get_all_destinations_for(departure))
        return self

    def __str__(self):

        header = "NAME: " + str(self.get_name()) + \
                 "  |  nb of departure airports: " + str(self.get_nb_departure_airports()) + \
                 "\n" + "--------------------------------------------------------------------------------------------" + "\n"
        body = ""

        for departure, destinations in sorted(self.get_departure_airports().items()):
            destinations_txt = ""
            for destination in destinations:
                destinations_txt += str(destination) + " ~~ "
            departure_text = str(departure) + " : " + destinations_txt + "\n"
            body += departure_text

        return header + body


airports = ["18 Meadows Aerodrome",
            "74 Ranch Airport",
            "7th Division State Police Headquarters Heliport",
            "A Z Minerals Corporation Airport",
            "A.I. Dupont Children's Hospital Heliport",
            "Aaron's Field",
            "Abbeville Municipal Airport",
            "Abc7-Tv Heliport",
            "Abel Ranch Airport",
            "Ac & R Components Heliport",
            "Ada Airport",
            "Adams Airport",
            "Adams Heliport",
            "Advent Health Altamonte Springs Heliport",
            "Aeleron Airport",
            "Aerie Airport",
            "Aero B Ranch Airport",
            "Aero-Lane Airport",
            "Aeronut Park Balloonport",
            "Aerospatiale Helicopter Corp Heliport",
            "Aerostone Ranch Airport",
            "Aha-Quin Airport",
            "Ainsworth Airport",
            "Air Columbia Heliport",
            "Air Columbia Heliport",
            "Air Oil Inc Nr 1 Heliport",
            "Air Oil Inc Nr 2 Heliport",
            "Air Park Field",
            "Air Park North",
            "Airc Helistop",
            "Airhaven Airport",
            "Airlane Enterprises Airport",
            "Airnautique, Inc. Airport",
            "Airpark East Airport",
            "Airpark Private Airport",
            "Alameda County Parking Garage Heliport",
            "Albanna Aviation Airport",
            "Albert Guido Memorial Heliport",
            "Albert Lodge Heliport",
            "Alcovy Airport",
            "Alderson Airport",
            "Alert Field",
            "Allen Ponderosa Heliport",
            "Allen Stagefield Army Heliport",
            "Alligator Drink Seaplane Base",
            "Allison Ranch Airport",
            "Allstate South Barrington Plaza Heliport",
            "Alpha Hotel Airport",
            "Alpine Range Airport",
            "Alta Sierra Airport",
            "Alta Vista Ranch Airport",
            "Alton Memorial Hospital Heliport",
            "Alum Ridge STOLport",
            "America's Chopper Pilots Heliport",
            "American Cyanamid Helistop",
            "Ames Private Airport",
            "Ami National Park Medical Center Heliport",
            "Amita Health Medical Center La Grange Heliport",
            "Amy Airport",
            "Anacacho Ranch Airport",
            "Ancam Antique Airfield",
            "Anderson Lake Airport",
            "Annapolis Seaplane Base",
            "Anniston AHP (Anniston Army Depot)",
            "Anson Hospital Heliport",
            "Answered Prayer Airport",
            "Apple 1 Heliport",
            "Apple Airport",
            "Applegate Airport",
            "Arco High Island Heliport",
            "Arco Ingleside Shorebase Heliport",
            "Argyle Airport",
            "Arizona Heart Hospital Heliport",
            "Arizona State Prison - Safford Heliport",
            "Arkavalley Airport",
            "Army Reserve Heliport",
            "Arnemann Farms Airport",
            "Arrow Aviation Company Heliport",
            "Arthur Airport",
            "Arvin Ranch Airport",
            "At&T Heliport",
            "Atchafalaya Flying Company Airport",
            "Atlantic City Medical Center Heliport",
            "Atlantic Field Mcolf Airport",
            "Atterbury Field (Camp Atterbury)",
            "Aubrey Mountain Airstrip",
            "Audubon County Memorial Hospital Heliport",
            "Augusta Medical Center Heliport",
            "Aurora Lakeland Medical Center Heliport",
            "Aurora Regional Medical Center Heliport",
            "Aurora St Luke's Medical Center Heliport",
            "Autolite Heliport",
            "Aventura Heliport",
            "Ayresouth Airport",
            "B & L Farms Airport",
            "B-B Airfield",
            "B. J. Mc Combs Sisterdale Airport",
            "Bahia Beach Heliport",
            "Bailey Generation Station Heliport",
            "Baker Ranches Airport",
            "Bally's Strip",
            "Ballymere Heliport",
            "Baltimore Washington Medical Center Heliport",
            "Bangart Field",
            "Baptist Hospital East Heliport",
            "Baptist Medical Center Heliport",
            "Baptist Memorial Hospital-North Ms Heliport",
            "Bar 3 Ranch Airport",
            "Barham Airport",
            "Barker Heliport",
            "Barnes Seaplane Base",
            "Barnstorm Field",
            "Barnstormers 5 Airport",
            "Barrett Field",
            "Barronena Ranch Airport",
            "Bartell Strip",
            "Barton Regional Medical Center Heliport",
            "Bass Field",
            "Bass Limited Airport",
            "Battle Lake Municipal Airport",
            "Baudette Flying Service Seaplane Base",
            "Baugher's Orchard Airport",
            "Bayfront Garage Heliport",
            "Baylor Medical Center Heliport",
            "Bayview Heliport",
            "Bear Creek Heliport",
            "Bear Lake Memorial Hospital Helipad",
            "Bear Mountain Heliport",
            "Bearwallow Farm Airport",
            "Beaux Ranch Field",
            "Beaver Lake Seaplane Base",
            "Beaver Meadow Heliport",
            "Beaverbrook Aerodrome",
            "Beaverhead Airstrip",
            "Beckley Farms Airport",
            "Beech Hill Airport",
            "Beefor Ranch Airport",
            "Beer Airport",
            "Belcher Airpatch Airport",
            "Belknap-Icarus Acres Airport",
            "Bell Helicopter Hurst Heliport",
            "Belleair Airport",
            "Bellmore Farms Airport",
            "Belridge Strip",
            "Beltzville Airport",
            "Benes Service Airport",
            "Bennetts Airport",
            "Bentley Heliport",
            "Berdick Field",
            "Berkeley Township Police Heliport",
            "Berlin Fairgrounds Heliport",
            "Bermudian Valley Airpark",
            "Bernardin Heliport",
            "Berry Field",
            "Bert Walter Berkowitz Heliport",
            "Beyer Farm Airport",
            "Bierly(Personal Use) Airport",
            "Big Bend Regional Medical Center Heliport",
            "Big Canoe Heliport",
            "Big Salmon Heliport",
            "Big Sandy Medical Center Heliport",
            "Black Butte Ranch Airport",
            "Black Diamond Airport",
            "Blanca Airport",
            "Blech Ranch Airport",
            "Bledsoe Ranch Airport",
            "Blessing Hospital At 11th St Heliport",
            "Blo Airport",
            "Bloom Airport",
            "Blue Haven Farm Airport",
            "Blue Hill Airport",
            "Blue Lick Airport",
            "Bluebird Airport",
            "Bob Norman Airstrip",
            "Boeing Santa Susana Heliport",
            "Boeing Seal Beach (Rooftop) Heliport",
            "Boggs Field",
            "Boggy Bottoms Airport",
            "Bohunk's Airpark",
            "Bondair Airport",
            "Boone County Hospital Heliport",
            "Boone National Guard Heliport",
            "Border Line Farm Airport",
            "Boss Airport",
            "Bossey's Seaplane Base",
            "Bossow Airport",
            "Boston Medical Center Hospital Heliport",
            "Bottoms Brothers Airport",
            "Boulais Heliport",
            "Bowles Airport",
            "Boyd's Turf Airport",
            "Bozeman Deaconess Hospital Heliport",
            "Brackenridge Hospital Heliport",
            "Bradbury-Rolf Memorial Heliport",
            "Bradley Lake Hydroelectri Project Airstrip",
            "Branch's Heliport",
            "Brandes Air Field",
            "Brazil Clay County Airport",
            "Brecht Strip",
            "Breckenridge Airport",
            "Breckheimer Airport",
            "Bredlow Farm Airport",
            "Breezecroft Airport",
            "Breezy Knoll Airport",
            "Brennan Farm Airport",
            "Bresett'S Mountainside Airport",
            "Brewer Airport",
            "Bridgeport Hospital Heliport",
            "Briley Farm Seaplane Base",
            "Brinkman Airport",
            "Bristol-Myers Squibb Company Heliport",
            "Brockton Usar Center Heliport",
            "Broken B Airport",
            "Brooklyn Airport",
            "Brookside Hospital Heliport",
            "Brookview Manor Heliport",
            "Brookville Reservoir Seaplane Base",
            "Brookwood Medical Center Heliport",
            "Brown Stagefield Army Heliport",
            "Brown Truck Sales Airport",
            "Bruce's Airport",
            "Brunner Airport",
            "Brunswick Community Hospital Heliport",
            "Buck Mountain Airport",
            "Bucks Airport",
            "Buddy Harmel Airport",
            "Buds Landing Airport",
            "Buehler Airport",
            "Buffalo Airport",
            "Bugtown Airport",
            "Buller's Airstrip",
            "Bulljump Airport",
            "Burke Heliport",
            "Burrs Strip",
            "Busboom RLA Restricted Landing Area",
            "Business Center of Alabama Heliport",
            "Butler Airport",
            "Buzz Field",
            "Byrne Field",
            "C & W Air Park",
            "Cade's Airport",
            "Cady Aerial RLA Restricted Landing Area",
            "Caffrey Heliport",
            "Cahoochie Airport",
            "Caldwell Municipal Airport",
            "California Title Building Heliport",
            "Calvert Memorial Hospital Heliport",
            "Camano Island Airfield",
            "Cambron Field",
            "Camp Beauregard Army National Guard Heliport",
            "Camp Chippewa Airport",
            "Camp Davis Mcolf Airport",
            "Camp Rilea Heliport",
            "Camp Tahigwa Landing Site Heliport",
            "Campbell Field",
            "Canadian Lakes Airport",
            "Canapitsit Airport",
            "Candlelight Farms Airport",
            "Cannon Creek Airpark",
            "Canon Heliport",
            "Canton-Plymouth-Mettetal Airport",
            "Cape Canaveral Hospital Heliport",
            "Capitol National Bank Building Heliport",
            "Card Aerodrome",
            "Carolina Cow Country Airport",
            "Carpenter Airport",
            "Carson Heliport",
            "Carsonville Airport",
            "Cartersville Airport",
            "Cartwheel Airport",
            "Cascade Field",
            "Cass Field",
            "Castle Well Airport",
            "Catfish Point Airport",
            "Cavage Personal Use Airport",
            "Cawleys South Prairie Airport",
            "Cedar Knoll Flying Ranch Airport",
            "Central City Municipal - Larry Reineke Field",
            "Century Helicopters Heliport",
            "Champion Ranch Airport",
            "Chandelle Estates Airport",
            "Channel 7 Heliport",
            "Channel Two Heliport",
            "Chapin Field",
            "Chappell Airport",
            "Charlton Strip",
            "Chehalem Airpark",
            "Chemical Bank - New Jersey Na Heliport",
            "Chenoweth Airport",
            "Cherokee Island Castle Heliport",
            "Cherokee Strip",
            "Cherokee Strip",
            "Cheryl-Lane Landings Airport",
            "Chesapeake City Heliport",
            "Chesapeake General Hospital Heliport",
            "Cheshire Medical Center Heliport",
            "Cheyenne River Health Center Heliport",
            "CHI St. Vincent Hospital Hot Springs Heliport",
            "Childrens Hospital Emergency Heliport",
            "Chinle Airport",
            "Christenson Point Seaplane Base",
            "Christian Hospital Northeast Heliport",
            "Christus Spohn Hospital Memorial Heliport",
            "CHS Union Heliport",
            "Chuck's Airport",
            "Churchill Airport",
            "Circle 'A' Ranch Airport",
            "Cirino Heliport",
            "City of Coalgate Airport",
            "Clark Airport",
            "Clark Airport",
            "Clark Heliport",
            "Clarks Dream Strip",
            "Classic Landings Airport",
            "Clay County Hospital Heliport",
            "Clear Creek Ranch Airport",
            "Cliche Cove Seaplane Base",
            "Clifford Field",
            "Clinton Elks Lodge Balloonport",
            "Clinton-Hickman County Airport",
            "Cloverleaf Farms Ii Inc. Heliport",
            "Cloverleaf Ranch Airport",
            "CMC Steel New Jersey Heliport",
            "Coach & Paddock Heliport",
            "Cochran Airport",
            "Coffman Airport",
            "Coffman Field",
            "Cole Farm Airport",
            "Colgate-Piscataway Heliport",
            "Collegeville Heliport",
            "Collins Landing Strip",
            "Colmery-O'Neil Vamc Heliport",
            "Colonial Air Park",
            "Colorado Plains Medical Center Heliport",
            "Columbus Municipal Airport",
            "Columbus Southwest Airport",
            "Columbus Stockyards Airport",
            "Comanche County Memorial Hospital Heliport",
            "Comanche Creek Airport",
            "Comfort Airpark",
            "Community Hospital Heliport",
            "Community Hospital of De Queen Heliport",
            "Community Methodist Hospital Heliport",
            "Compaq Andover Heliport",
            "Condell Medical Center Heliport",
            "Confer's Place Airport",
            "Connelly Field",
            "Conoco Heliport",
            "Conoco Inc Heliport",
            "Conover Air Lodge Airport",
            "Conrads Airport",
            "Converse Airport",
            "Cooper Airport",
            "Cooper Flying Service Airport",
            "Coopers Landing",
            "Copper Basin Airport",
            "Cordes Airport",
            "Corkscrew Trace Airpark",
            "Corning Municipal Airport",
            "Corntassel Airport",
            "Corral Creek Airport",
            "Corydon Airport",
            "Cottingham Airport",
            "Cotton Strip",
            "Cottonwood Airport",
            "Cottonwood Airport",
            "Cottonwood Field",
            "Country Air Estates Airport",
            "Country Breeze Airport",
            "Coyote Ridge Airport",
            "Coyote Run Airport",
            "Craig Cg Heliport",
            "Crash In International Airport",
            "Crawford Airport",
            "Crazy Horse Airport",
            "Crazy Horse Heliport",
            "Creekside Airport",
            "Creighton Airport",
            "Creole Heliport",
            "Crested Butte Airpark",
            "Crevice Creek Airport",
            "Cribbet Airport",
            "Crittenden Regional Hospital Heliport",
            "Cromwell Heliport",
            "Cross Creek Farms Airport",
            "Cross Wind Airport",
            "Cross-Country Estates Airport",
            "Crosswind Lake Airport",
            "Crystal Airport",
            "Crystal Lake Airpark",
            "Crystal Lakes Resort Airport",
            "Cuchens Airport",
            "Cuddihy Field",
            "Curtis Airport",
            "Curtis Ranch Field",
            "Cushing Field Ltd Airport",
            "Cut and Shoot Airport",
            "Cuttyhunk Heliport",
            "Cuylers Airport",
            "Cylon Heliport",
            "D.W. Mcmillian Memorial Hospital Heliport",
            "Dairyview Airport",
            "Dakota Air Ranch Airport",
            "Damien Heliport",
            "Danbury Hospital Heliport",
            "Daniel Emergency Response Team Heliport",
            "Daniel's Landing Airport",
            "Darbro Field",
            "Darla's Airport",
            "Dave's Airport",
            "Davis Airport",
            "Davis Field Ultralightport",
            "Dawson Farms Airport",
            "De De Airport",
            "De Kalb General Hospital Heliport",
            "De Leon Municipal Airport",
            "De Motte Airport",
            "Deaconess Hospital Heliport",
            "Dean Ranch Airport",
            "Decatur General Hospital Heliport",
            "Defiance Regional Medical Center Heliport",
            "Dekalb Regional Medical Center Heliport",
            "Delaware Valley Hospital Heliport",
            "Delaware Valley Medical Center Heliport",
            "Deldot Helistop",
            "Delphi Municipal Airport",
            "Delta County Memorial Hospital Heliport",
            "Delta Shores Airport",
            "Dennis Farms Airport",
            "Detour Airport",
            "Devil's Reach Landing Airport",
            "Devonshire Area Heliport",
            "Dew Drop Airport",
            "Diamond Bluff Airport",
            "Diamond H Ranch Airport",
            "Diamond N Ranch Airport",
            "Diamond P. Field",
            "Diedrich Seaplane Base",
            "Dimascio Field",
            "Diving Rock Seaplane Base",
            "Dix Field",
            "Dobie's Airport",
            "Doc's Airport",
            "Doctors Memorial Hospital #2 Heliport",
            "Dodsworth Airport",
            "Doering Farms Airfield",
            "Dolgeville Airport",
            "Dolphin Stadium Heliport",
            "Domeyer Airport",
            "Don Babin-Private Airport",
            "Dongola Heliport",
            "Dooley Airport",
            "Doral Resort & Country Club Heliport",
            "Dorlon Airpark",
            "Dorsey Creek Ranch Airport",
            "Dosher Heliport",
            "Double H Ranch Airport",
            "Double S Airport",
            "Doug Bolton Field",
            "Dow Chemical Heliport",
            "Draggintail Acres Airport",
            "Dragonfly Field",
            "Dreessen Field",
            "Drew Medical Center Heliport",
            "Drillmore Acres Airport",
            "Drisko Airport",
            "Dry Pen Airport",
            "Dry Swamp Airport",
            "Duckwater Airport",
            "Duda Airstrip",
            "Dufour Airport",
            "Dugger Field",
            "Dunbar Ranch Airport",
            "Dutch Gap Airstrip",
            "Dwight Field",
            "Dynasty Heliport",
            "E Northrop Grumman Airport",
            "Eagle Field",
            "Eagle Field",
            "Eagle Field",
            "Eagle Neck Airport",
            "Eagle Pass Airport",
            "Eagle Soaring Airport",
            "Eagles Landing Heliport",
            "Eakin Airport",
            "Earle Airpark",
            "East Field",
            "East Oregon Cattle Co Airport",
            "East Tennessee Children's Hospital Heliport",
            "East-West Paris Airport",
            "Eastman Seaplane Base",
            "Ech Stagefield Army Heliport",
            "Eckerts Airstrip",
            "Ecko Field",
            "Ed Shadle Airport",
            "Eddie Dew Memorial Airpark",
            "Edmond Airport",
            "Eds Heliport",
            "Elkins Field",
            "Ellinwood Municipal Airport",
            "Ellis Field",
            "Ellis Fly-In Airport",
            "Ellis/Harvey Airport",
            "Elm Creek Airpark",
            "Elmore Medical Center Heliport",
            "Elsanor Airport",
            "Ely Bloomenson Community Hospital Heliport",
            "Emergency Helipad",
            "Emerson Heliport",
            "Emmanuel Airport",
            "Emory Ranch Airport",
            "Emp. Coco Beach Golf Club LLC Heliport",
            "Empire Airport",
            "English Heliport",
            "Enumclaw Community Hospital Heliport",
            "Epps Airpark",
            "Era Helicopters Fourchon Helibase Heliport",
            "Erco Field",
            "Erickson Field",
            "Erlanger Medical Center Heliport",
            "Essex Generating Station Heliport",
            "Etowah Fields Airport",
            "Eureka Springs Hospital Heliport",
            "Evanston/Glenbrook Heliport",
            "Evergreen Fourchon Heliport",
            "Evergreen Heliport",
            "Evergreen Venice Heliport",
            "Everitt Airport",
            "Exempla Good Samaritan Heliport",
            "Exit 3 Airport",
            "Expressway Airpark",
            "Exxon Heliport",
            "Ez Lope Ranch Airport",
            "F.B. Fowler Heliport",
            "Faber Vineyards Airport",
            "Fair Haven Municipal Airport",
            "Fairbanks Airfield",
            "Fairplains Airpark",
            "Falcon Heliport",
            "Falcon Lake Strip",
            "Falin Landing Strip",
            "Fayette County Memorial Hospital Heliport",
            "Ferguson Farms Airport",
            "Ferraraccio Field",
            "Ferrell Field",
            "Ferris Red Oak Municipal Heliport",
            "Ferros Ranch-Aero Airport",
            "Field of Dreams Airport",
            "Findlay Heliport",
            "Findley Field",
            "Fiorini Ranch Airport",
            "Firelands Community Hospital Nr 1 Heliport",
            "Fish Ranch Airport",
            "Fisher Airport",
            "Fisher Airport",
            "Fishermen's Hospital Emergency Helistop",
            "Fitterer's Strip",
            "Fla-Net Airport",
            "Flaherty Field",
            "Flat Creek Field",
            "Flat Top Airstrip",
            "Flatrock Air Strip",
            "Flatwood Field",
            "Fletcher Airport",
            "Flight Park Inc Airport",
            "Floathaven Seaplane Base",
            "Flomaton Airport",
            "Flow Through Terminal Heliport",
            "Flower Mound Airport",
            "Flyers Airport",
            "Flying 'K' Ranch Ultralightport",
            "Flying 'T' Ranch Airport",
            "Flying Acres Airport",
            "Flying B Ranch Airport",
            "Flying B Ranch Landing Strip",
            "Flying Baron Estates Airport",
            "Flying Bucket Ranch Airport",
            "Flying D Airport",
            "Flying Feathers Airport",
            "Flying G Airport",
            "Flying G Ranch STOLport",
            "Flying H Farms Airport",
            "Flying Joseph Ranch Airport",
            "Flying M & M Ranch Airport",
            "Flying M Ranch Airport",
            "Flying N Estates Airport",
            "Flying N Ranch Airport",
            "Flying O Airport",
            "Flying R Airport",
            "Flying S Air Ranch Airport",
            "Flying S Ranch Airport",
            "Flying Ten Airport",
            "Flying U Airport",
            "Flying W Air Park Inc Airport",
            "Flying W Airport",
            "Flying Y Ranch Airport",
            "Fmc Nr 1 Heliport",
            "Foggy River Airport",
            "Folmar Airport",
            "Foltz Heliport",
            "Foothill Presbyterian Hospital Heliport",
            "Forestry-Strip Airport",
            "Fort Duncan Medical Center Heliport",
            "Fort Walton Beach Airport",
            "Four Corners Airport",
            "Four Seasons Airport",
            "Four Star Heliport",
            "Fowler Airport",
            "Fowler Field",
            "Fowlers Nw 40 Airport",
            "Fox Acres Airport",
            "Fox Hole Airport",
            "Foxx Valley Airport",
            "Frager Field",
            "Franciscan Health Rensselaer Heliport",
            "Franconia Airport",
            "Franklin County Memorial Hospital Heliport",
            "Franklin Field",
            "Frazier Lake Airpark",
            "Frederick Airpark",
            "Freedom Air Ranch Airport",
            "Freefall Oz Airport",
            "Freeman Neosha Hospital Heliport",
            "Freeport Sulphur Heliport",
            "French Field",
            "Frost Field",
            "Fry Airport",
            "Fry Field",
            "Fsa - Everett Heliport",
            "Fulton Airport",
            "Fulton Seaplane Base",
            "Fulton-Itawamba County Airport",
            "FWOMC Heliport",
            "G & J Fly A Way Ultralightport",
            "G & S Space Port Airport",
            "G S A Laguna Niguel G/L Helistop",
            "Gadsden Regl Medical Center Heliport",
            "Gage Airport",
            "Galion Community Hospital Heliport",
            "Galleria Heliport",
            "Galloway Airport",
            "Gardner Farm Airport",
            "Garner Field",
            "Garner Landing Seaplane Base",
            "Gary Gale Seaplane Base",
            "Gator Lake Heliport",
            "Gattis Strip",
            "Gay Hill Farm Airport",
            "Gearhart-Hollow Heliport",
            "Geisinger Community Medical Center Nap Heliport",
            "Geo-Seis Helicopters Heliport",
            "Georgia Mountain Heliport",
            "Gerhart Airport",
            "Gibbons Airport",
            "Gibbons Field",
            "Gibbs Field",
            "Gilbert Development Corp Heliport",
            "Gilbert Emergency Hospital Heliport",
            "Gilbertson Field",
            "Gile Pond Airport",
            "Gimlin Airport",
            "Gittleson Farms Airport",
            "Glacier Heli Tours Heliport",
            "Glaser Field",
            "Glasgow Industrial Airport",
            "Glen Fed Heliport",
            "Glide Aero Airport",
            "Go Gulf Heliport",
            "Goddard Field (Airport)",
            "Goerger Airport",
            "Goldberg Stagefield Army Heliport",
            "Golden North Airfield",
            "Goldfield Airport",
            "Goldstone /Gts/ Airport",
            "Goltl Airport",
            "Good Pasture Airport",
            "Good Samaritan Hospital Heliport",
            "Good Samaritan Hospital Heliport",
            "Gooding County Memorial Hospital Heliport",
            "Gord Airport",
            "Gordon Airport",
            "Gorman Airport",
            "Gottlieb Heliport",
            "Gottwald Field",
            "Grace Hospital Heliport",
            "Grady Memorial Hospital Heliport",
            "Grand Marais/Cook County Seaplane Base",
            "Grandpas' Farm Mendota Airport",
            "Grant Airport",
            "Grant Pad Heliport",
            "Grass Patch Airport",
            "Grass Roots Airpark",
            "Grass Roots Airport",
            "Grassy Pond Heliport",
            "Graves Landing Strip",
            "Grawunder Field",
            "Gray Airport",
            "Gray Butte Field",
            "Greater Laurel Beltsville Hospital Heliport",
            "Green Acres Airport",
            "Green Acres Airport",
            "Green Acres Airport",
            "Greenbush Municipal Airport",
            "Greener Pastures Airpark",
            "Greenville-Rainbow Airport",
            "Greg's Flying Service Airport",
            "Gregg Airport",
            "Greggs Nr 1 Airport",
            "Griffin Airport",
            "Griffin Airport",
            "Grindstone Lake Seaplane Base",
            "Grossmont Hospital Heliport",
            "Groundhog Mountain Airport",
            "Gull Bay Landing Airport",
            "Gwinnett Community Hospital D/B/A Eastside Medical Center Heliport",
            "Ha-Rail Airport",
            "Haas Airport",
            "Hackensack UMC Palisades Heliport",
            "Hadley Airport",
            "Hagen Private Airport",
            "Hains Airstrip",
            "Hal Joy Airfield",
            "Hale Field",
            "Hall Airport",
            "Halls Flying Ranch Airport",
            "Hamilton County Sheriff's Patrol Heliport",
            "Hamilton Field",
            "Hamilton Headquarter Troop C Heliport",
            "Hamilton Memorial Hospital Heliport",
            "Hammer Airport",
            "Hammersmith Heliport",
            "Handy Strip",
            "Hanel Field",
            "Hannen Airport",
            "Hannibal Regional Hospital Heliport",
            "Hansen Airport",
            "Hansen Heliport",
            "Hansen Heliport",
            "Hanson Airport",
            "Hardin Memorial Hospital Heliport",
            "Hardy Airport",
            "Harman Airport",
            "Harms Airstrip",
            "Harold Bunger Airport",
            "Harold Emmerich Airport",
            "Harold Miller Heliport",
            "Harper's Fly-In Ranch Airport",
            "Harpers Airport",
            "Harrington Field",
            "Harris Corn Field",
            "Harris County Courthouse Heliport",
            "Hartford Hospital Heliport",
            "Harvest Lake Seaplane Base",
            "Harvey Young Airport",
            "Hatch Stagefield Army Heliport",
            "Haunstein Ultralightport",
            "Hawk Haven Airport",
            "Hawker Airport",
            "Hawkeye Airport",
            "Hawks Meadow Airport",
            "Hawks Run Airport",
            "Hay Field",
            "Hayden Farm Airport",
            "Hayden Mountain Airport",
            "Hayenga's Cant Find Farms Airport",
            "Health Sciences Center University Hospital Heliport",
            "Healthalliance Hospital-Leominster Heliport",
            "Heape Field",
            "Hector Municipal Airport",
            "Heifer Creek Ranch Airport",
            "Heilman Airport",
            "Heinzman Airport",
            "Helblad Airport",
            "Heli-Dyne Systems Inc Heliport",
            "Helicopter Applicators Inc Heliport",
            "Heliport-Facility 5a Heliport",
            "Hemmer RLA Restricted Landing Area",
            "Hendershots Heliport",
            "Hendry County Fire-Ems Heliport",
            "Henning Municipal Airport",
            "Henry County Memorial Hospital Heliport",
            "Henry Ford Hospital Heliport",
            "Henry Mayo Newhall Memorial Hospital Heliport",
            "Henry Valve Company Heliport",
            "Hensley Airpark",
            "Herbst Heliport",
            "Herman Municipal Airport",
            "Hess Port Reading Heliport",
            "Hi-Acres Airport",
            "HIA Airport",
            "Hickory Hills Airport",
            "Hickory Level Airfield",
            "Hidden Quarry Airport",
            "Hide-A-Way Hills Resort Airport",
            "Hideaway Ultralightport",
            "High Valley Airport",
            "Highbluff Stagefield Army Heliport",
            "Highfalls Stagefield Army Heliport",
            "Highland Medical Center Heliport",
            "Highway Patrol Troop C Headquarters Heliport",
            "Hilde-Griff Field",
            "Hill City-Quadna Mountain Airport",
            "Hilliard Airpark",
            "Hillside Stables Airport",
            "Hilltop Lakes Airport",
            "Hinckley Airport",
            "Hines Farm Airport",
            "Hitch Feeders Ii Inc. Airport",
            "Hoag Memorial Hospital Heliport",
            "Hobby Hideaway RLA Airport",
            "Hock Airport",
            "Hoffman Private Airport",
            "Hogue Farm Airport",
            "Holcomb Field",
            "Holden Heliport",
            "Holiday Inn Lakeview Heliport",
            "Holiday Sky Ranch Airport",
            "Holland Field",
            "Holland Ranch Airport",
            "Hollow Top Airport",
            "Holly Lake Ranch Airport",
            "Holt Airpark",
            "Holy Family Hospital Heliport",
            "Holy Family Hospital Heliport",
            "Homan Field",
            "Homeport Airport",
            "Hoolie Airport",
            "Hooper Stagefield Army Heliport",
            "Hoopeston Community Memorial Hospital Heliport",
            "Hooterville South Airport",
            "Hop House Airpark",
            "Hop-Along Airport",
            "Horne Properties Heliport",
            "Horsefeathers Ranch Airport",
            "Horseshoe Bend Heliport",
            "Hospital Pad Heliport",
            "Hostetler Airport",
            "Houston Heliport",
            "Houston Oil & Minerals Port Bolivar Nr 2 Heliport",
            "Howard Memorial Hospital Heliport",
            "Howell Airport",
            "Hoyt Airport",
            "Hscmh Heliport",
            "Huenefeld Airport",
            "Huey Airport",
            "Hughes Ultralightport",
            "Humm Airport",
            "Hummel Seaplane Base",
            "Hummingbird Heliport",
            "Hundley Residence Heliport",
            "Hunt Airport",
            "Hunt Farms Airport",
            "Hunt Stagefield Army Heliport",
            "Hunt Strip",
            "Hunt's Sky Ranch Airport",
            "Hunter STOLport",
            "Huntsville Field",
            "Huntsville Memorial Hospital Heliport",
            "Hyde Ranch Airport",
            "Ibm King St Heliport",
            "Icy Bay Airport",
            "Indian Path Medical Center Heliport",
            "Industrial Helicopters Inc. Airport",
            "Ingersoll Heliport",
            "International Falls Seaplane Base",
            "Interstate Airport",
            "Ira Biffle Airfield",
            "Iroquois Landing Seaplane Base",
            "Isbell Ranch Airport",
            "Iuka Hospital Heliport",
            "J & S Field",
            "J R Ranch Airport",
            "J V Ranch Airport",
            "J-22 Ranch Airport",
            "J-B Airstrip",
            "J. H. Hendrie Farms Airport",
            "Jack W. Watson Airport",
            "Jackson Heliport",
            "Jackson Parish Hospital Heliport",
            "Jackson Seaplane Base",
            "Jacksonville / Hunter Field",
            "Jacobia Field",
            "Jake Garn Airport",
            "Jasmine Hill Airport",
            "Jaxon Landing Heliport",
            "Jayarz Airport",
            "Jbh Aerospace Heliport",
            "Jecan Airport",
            "Jefferson County Memorial Hospital Heliport",
            "Jenkins Airport",
            "Jenkins Field",
            "Jennersville Hospital Heliport",
            "Jer-Mar Airpark",
            "Jersey Tpke New Brunswick Helistop",
            "Jerseyville Aviation Inc Airport",
            "Jewett Mesa Airport",
            "Jfk Medical Center Heliport",
            "Jim Roach Field",
            "JLS Farms Airport",
            "Jmj Landing Airport",
            "Joe Clouds Seaplane Base",
            "Joe D Lewis Airport",
            "Joe Gottlieb Field",
            "John C Lincoln Hospital Heliport",
            "John Fields Ranch Airport",
            "John M. Foree Airport",
            "John Nichol's Field Airport",
            "John's Airport",
            "Johnson Field",
            "Johnson Fox Field",
            "Johnson Memorial Airport",
            "Johnston Farm Airport",
            "Jones Landing",
            "Joy Farms Airport",
            "Jr's Airport",
            "Jrmc Heliport",
            "Juhnke Airport",
            "Jumbolair-Greystone Airport",
            "June Lake Airpark",
            "K3 Helipad Heliport",
            "Kaan Airport",
            "Kahoka Municipal Airport",
            "Kalakaket Creek AS Airport",
            "Kalifonsky Meadows Airport",
            "Kallander Field",
            "Kauffman Heliport",
            "Kaufield Airport",
            "Kaupulehu Heliport",
            "KBMT-TV Heliport",
            "Keller Airport",
            "Keller Brothers Airport",
            "Kelleys Airport",
            "Kellie Mann Airfield",
            "Kellums Airport",
            "Kelly Heliport",
            "Kenai River Airpark",
            "Kendrigan Airport",
            "Kenley Airport",
            "Kenyon Heliport",
            "Kermizian Airport",
            "Kester Fly Inn Airport",
            "Ketchikan /Temsco H/ Heliport",
            "Kewanee Hospital Heliport",
            "Key Way Airport",
            "Keyes Ranch Airport",
            "Keyhole Airport",
            "Keyser Airport",
            "Killarny Farm Airport",
            "Kimp Airport",
            "Kimzey Airport",
            "King Ultralightport",
            "Kingston Ranch Airport",
            "Kishwaukee Community Hospital Heliport",
            "Kistler Ranch Airport",
            "Kitchen Creek Helibase Heliport",
            "Kitner Airport",
            "Kittyhawk Airport",
            "Klaverack Airport",
            "Kml Airport",
            "Knolle Ranch Airport",
            "Knox Landing Airport",
            "Knoxville Area Community Hospital Heliport",
            "Koenig Airport",
            "Korver Airport",
            "Kosik Private Airport",
            "Krens Farm Airport",
            "Krey Field Airport",
            "Kropf Airport",
            "Kugel-Strong Airport",
            "Kvue-Tv Heliport",
            "L P Askew Farms Airport",
            "L-Z Blue Thunder Heliport",
            "L. A. Times Costa Mesa Heliport",
            "La National Guard Heliport",
            "La Sal Junction Airport",
            "LA State Police Troop F Heliport",
            "La State Police Troop G Heliport",
            "Lac Vieux Desert Seaplane Base",
            "Lag Iii Heliport",
            "Lagrone Ranch Airport",
            "Lake Airport",
            "Lake Bay Gall Airport",
            "Lake City Medical Center Heliport",
            "Lake Conway South Seaplane Base",
            "Lake Gage Seaplane Base",
            "Lake Louise Seaplane Base",
            "Lake Mills Municipal Airport",
            "Lake Monroe Seaplane Base",
            "Lake Murray State Park Airport",
            "Lake Park Helistop",
            "Lake Persimmon Airstrip",
            "Lake Sexton Airport",
            "Lake Tuscaloosa Seaplane Base",
            "Lake Wawasee Seaplane Base",
            "Lakeside Beach Airport",
            "Lakeside Marina Seaplane Base",
            "Lakeview Airport",
            "Lakewood Lodge Airport",
            "Lambdins Field",
            "Lambert Fechter Municipal Airport"]

import string
import random


def randomString(stringLength = 10):
    """Generate a random string of fixed length """
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(stringLength))


airlines = []
for N in range(10):
    airline = Airline(randomString(20))
    for n in range(random.randint(1, 11)):
        airline.add_destination_for(random.choice(airports), random.choices(airports, k = n))
    airlines.append(airline)

for airline in airlines:
    # print(airline)
    pass

print(airlines[-2], airlines[-1])
print(airlines[-2] + airlines[-1])
